logging:
  level:
    com.recipia.recipe: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: debug
    org.springframework.cloud.sleuth: debug

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sqs:
        nickname-sqs-name: nickname-change-sqs
      s3:
        bucketName: recipia-file


feign:
  member_url: ${MEMBER_URL}