logging:
  level:
    com.recipia.recipe: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.cloud.sleuth: info

#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  application:
    name: recipe

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sns:
        topics:
          nickname-change: arn:aws:sns:${REGION}:${ACCOUNT_ID}:sns-test
      #          topic1: arn:aws:sns:${REGION}:${ACCOUNT_ID}:topic1
      sqs:
        nickname-sqs-name: sqs-test

#  zipkin:
#    base-url: http://localhost:9411/
#
#  sleuth:
#    enabled: true
#    sampler:
#      probability: 1.0

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql이 실행됨

  h2:
    console:
      enabled: true

