logging:
  level:
    com.recipia.recipe: info
    org.springframework.web.servlet: info
    org.hibernate.orm.jdbc.bind: info
    org.springframework.cloud.sleuth: info

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${REGION}
      sqs:
        nickname-sqs-name: nickname-change-sqs
        signup-sqs-name: signup-sqs
        member-withdraw-sqs-name: member-withdraw-sqs

      s3:
        bucketName: recipia-file

#  redis:
#    host: 실제ip
#    port: 6379
#    password: redis
#    database: 0   # 0번 데이터베이스 사용 (상용)


feign:
  member_url: ${MEMBER_URL}

mongo:
  documentId: 65b628620ecc5780c4c53850