logging:
  level:
    com.recipia.recipe: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace

#spring:
#  datasource:
#    url: ${LOCAL_DB_URL}
#    username: ${LOCAL_DB_USERNAME}
#    password: ${LOCAL_DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    defer-datasource-initialization: true
#    hibernate.ddl-auto: none
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
#        highlight_sql: true
#
#  sql.init.mode: always

---

spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/RecipiaRecipe
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  kafka:
    bootstrap-servers: localhost:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: recipia

server:
  port: 8082
---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql이 실행됨

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
